name: Build Android Project

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/TAGS.md'
      - 'fastlane/**'
      - /.github/workflows/build.yml
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/TAGS.md'
      - 'fastlane/**'



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 19
      uses: actions/setup-java@v4
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle without running tests
      run: ./gradlew build --exclude-task test 

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
