name: Build Android Project

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/TAGS.md'
      - 'fastlane/**'
      - /.github/workflows/build.yml
      - /.github/workflows/release-draft.yml
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/TAGS.md'
      - 'fastlane/**'



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle without running tests
      run: ./gradlew build --exclude-task test 
